[package]
name = "lights-controller"
version = "0.1.0"
authors = ["Ascot"]
edition = "2021"

[dependencies]
actix-rt = "2.6"
clap = { version = "^4.5", features = ["derive"] }
confy = "0.6"
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webthing = "0.15"
